import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    data: [
        {
            trip_ID: "trip1",
            arrival: "2023-10-01T10:00:00Z",
            departure: "2023-10-01T12:00:00Z",
            travel_month: "October",
            destination: "New York",
            acc_manager: "John Doe",
            booking_data: "2023-09-15T08:00:00Z",
            agent: "Jane Smith",
            lead_pax: "Alice Johnson",
            order_value: 1500,
            payment_value: 1500,
            transfer_price: 100,
            trip_status: "Confirmed",
            ops_spoc: "Bob Brown",
            booking_status: "Active",
            vouchers: "Voucher123",
        },
        {
            trip_ID: "trip1a",
            arrival: "2023-10-01T11:00:00Z",
            departure: "2023-10-01T13:00:00Z",
            travel_month: "October",
            destination: "Los Angeles",
            acc_manager: "Mark Wilson",
            booking_data: "2023-09-16T08:30:00Z",
            agent: "Sarah Miller",
            lead_pax: "Robert Johnson",
            order_value: 1600,
            payment_value: 1600,
            transfer_price: 110,
            trip_status: "Confirmed",
            ops_spoc: "Carol Davis",
            booking_status: "Active",
            vouchers: "Voucher124",
        },
        {
            trip_ID: "trip1b",
            arrival: "2023-10-02T11:00:00Z",
            departure: "2023-10-02T13:00:00Z",
            travel_month: "October",
            destination: "Boston",
            acc_manager: "John Doe",
            booking_data: "2023-09-16T09:00:00Z",
            agent: "Jane Smith",
            lead_pax: "Alice Johnson",
            order_value: 1550,
            payment_value: 1550,
            transfer_price: 120,
            trip_status: "Confirmed",
            ops_spoc: "Bob Brown",
            booking_status: "Active",
            vouchers: "Voucher124",
        },
        {
            trip_ID: "trip2",
            arrival: "2023-11-05T14:30:00Z",
            departure: "2023-11-05T16:30:00Z",
            travel_month: "November",
            destination: "London",
            acc_manager: "Emily Clark",
            booking_data: "2023-10-20T09:15:00Z",
            agent: "Tom Harris",
            lead_pax: "Michael Lee",
            order_value: 2000,
            payment_value: 1800,
            transfer_price: 150,
            trip_status: "Pending",
            ops_spoc: "Sara White",
            booking_status: "Pending",
            vouchers: "Voucher456",
        },
        {
            trip_ID: "trip3",
            arrival: "2023-12-10T09:00:00Z",
            departure: "2023-12-10T11:00:00Z",
            travel_month: "December",
            destination: "Paris",
            acc_manager: "David Green",
            booking_data: "2023-11-25T10:30:00Z",
            agent: "Linda Black",
            lead_pax: "Chris Evans",
            order_value: 1750,
            payment_value: 1750,
            transfer_price: 120,
            trip_status: "Confirmed",
            ops_spoc: "Nancy Blue",
            booking_status: "Active",
            vouchers: "Voucher789",
        },
        {
            trip_ID: "trip4",
            arrival: "2024-01-15T13:00:00Z",
            departure: "2024-01-15T15:00:00Z",
            travel_month: "January",
            destination: "Tokyo",
            acc_manager: "Olivia Brown",
            booking_data: "2023-12-28T11:00:00Z",
            agent: "Peter White",
            lead_pax: "Sophia Turner",
            order_value: 2200,
            payment_value: 2100,
            transfer_price: 200,
            trip_status: "Confirmed",
            ops_spoc: "George King",
            booking_status: "Active",
            vouchers: "Voucher101",
        },
        {
            trip_ID: "trip5",
            arrival: "2024-02-20T08:00:00Z",
            departure: "2024-02-20T10:00:00Z",
            travel_month: "February",
            destination: "Sydney",
            acc_manager: "Lucas Gray",
            booking_data: "2024-02-01T12:00:00Z",
            agent: "Rachel Adams",
            lead_pax: "Daniel Kim",
            order_value: 2500,
            payment_value: 2500,
            transfer_price: 180,
            trip_status: "Pending",
            ops_spoc: "Megan Fox",
            booking_status: "Pending",
            vouchers: "Voucher202",
        },
        {
            trip_ID: "trip6",
            arrival: "2024-03-12T17:00:00Z",
            departure: "2024-03-12T19:00:00Z",
            travel_month: "March",
            destination: "Dubai",
            acc_manager: "Sophia Miller",
            booking_data: "2024-02-25T13:30:00Z",
            agent: "James Scott",
            lead_pax: "Emma Watson",
            order_value: 3000,
            payment_value: 2900,
            transfer_price: 250,
            trip_status: "Confirmed",
            ops_spoc: "Henry Ford",
            booking_status: "Active",
            vouchers: "Voucher303",
        },
        {
            trip_ID: "trip7",
            arrival: "2024-04-18T11:00:00Z",
            departure: "2024-04-18T13:00:00Z",
            travel_month: "April",
            destination: "Rome",
            acc_manager: "Benjamin Lee",
            booking_data: "2024-03-30T14:00:00Z",
            agent: "Olivia Smith",
            lead_pax: "William Brown",
            order_value: 1600,
            payment_value: 1600,
            transfer_price: 130,
            trip_status: "Cancelled",
            ops_spoc: "Ella Green",
            booking_status: "Cancelled",
            vouchers: "Voucher404",
        },
        {
            trip_ID: "trip8",
            arrival: "2024-05-22T15:00:00Z",
            departure: "2024-05-22T17:00:00Z",
            travel_month: "May",
            destination: "Berlin",
            acc_manager: "Charlotte Wilson",
            booking_data: "2024-05-01T15:30:00Z",
            agent: "Jack Taylor",
            lead_pax: "Lucas Martin",
            order_value: 1850,
            payment_value: 1850,
            transfer_price: 140,
            trip_status: "Confirmed",
            ops_spoc: "Grace Hall",
            booking_status: "Active",
            vouchers: "Voucher505",
        },
        {
            trip_ID: "trip9",
            arrival: "2024-06-10T10:00:00Z",
            departure: "2024-06-10T12:00:00Z",
            travel_month: "June",
            destination: "Madrid",
            acc_manager: "Amelia Young",
            booking_data: "2024-05-20T16:00:00Z",
            agent: "Ethan Harris",
            lead_pax: "Mia Clark",
            order_value: 2100,
            payment_value: 2000,
            transfer_price: 160,
            trip_status: "Pending",
            ops_spoc: "Liam Lewis",
            booking_status: "Pending",
            vouchers: "Voucher606",
        },
        {
            trip_ID: "trip10",
            arrival: "2024-07-05T09:00:00Z",
            departure: "2024-07-05T11:00:00Z",
            travel_month: "July",
            destination: "Toronto",
            acc_manager: "Mason Walker",
            booking_data: "2024-06-15T17:00:00Z",
            agent: "Ava Robinson",
            lead_pax: "Noah Lee",
            order_value: 1950,
            payment_value: 1950,
            transfer_price: 110,
            trip_status: "Confirmed",
            ops_spoc: "Zoe King",
            booking_status: "Active",
            vouchers: "Voucher707",
        },
        {
            trip_ID: "trip11",
            arrival: "2024-08-14T13:00:00Z",
            departure: "2024-08-14T15:00:00Z",
            travel_month: "August",
            destination: "Bangkok",
            acc_manager: "Logan Harris",
            booking_data: "2024-07-25T18:00:00Z",
            agent: "Chloe Martinez",
            lead_pax: "Elijah White",
            order_value: 2300,
            payment_value: 2300,
            transfer_price: 170,
            trip_status: "Confirmed",
            ops_spoc: "Harper Scott",
            booking_status: "Active",
            vouchers: "Voucher808",
        },
        {
            trip_ID: "trip12",
            arrival: "2024-09-09T16:00:00Z",
            departure: "2024-09-09T18:00:00Z",
            travel_month: "September",
            destination: "Cape Town",
            acc_manager: "Ella Thompson",
            booking_data: "2024-08-20T19:00:00Z",
            agent: "Jacob Perez",
            lead_pax: "Aiden Garcia",
            order_value: 2400,
            payment_value: 2300,
            transfer_price: 190,
            trip_status: "Pending",
            ops_spoc: "Scarlett Evans",
            booking_status: "Pending",
            vouchers: "Voucher909",
        },
        {
            trip_ID: "trip13",
            arrival: "2024-10-21T12:00:00Z",
            departure: "2024-10-21T14:00:00Z",
            travel_month: "October",
            destination: "Singapore",
            acc_manager: "William Martinez",
            booking_data: "2024-10-01T20:00:00Z",
            agent: "Sofia Lee",
            lead_pax: "Jackson Brown",
            order_value: 2600,
            payment_value: 2500,
            transfer_price: 210,
            trip_status: "Confirmed",
            ops_spoc: "Layla Wilson",
            booking_status: "Active",
            vouchers: "Voucher1010",
        },
        {
            trip_ID: "trip14",
            arrival: "2024-11-17T08:00:00Z",
            departure: "2024-11-17T10:00:00Z",
            travel_month: "November",
            destination: "Istanbul",
            acc_manager: "James Anderson",
            booking_data: "2024-10-28T21:00:00Z",
            agent: "Mila Thomas",
            lead_pax: "Sebastian Moore",
            order_value: 1700,
            payment_value: 1700,
            transfer_price: 100,
            trip_status: "Cancelled",
            ops_spoc: "Penelope Clark",
            booking_status: "Cancelled",
            vouchers: "Voucher1111",
        },
        {
            trip_ID: "trip15",
            arrival: "2024-12-03T14:00:00Z",
            departure: "2024-12-03T16:00:00Z",
            travel_month: "December",
            destination: "Los Angeles",
            acc_manager: "Alexander Wright",
            booking_data: "2024-11-15T22:00:00Z",
            agent: "Aria Walker",
            lead_pax: "Matthew Young",
            order_value: 2800,
            payment_value: 2700,
            transfer_price: 230,
            trip_status: "Confirmed",
            ops_spoc: "Victoria Hill",
            booking_status: "Active",
            vouchers: "Voucher1212",
        },
        {
            trip_ID: "trip16",
            arrival: "2025-01-11T10:00:00Z",
            departure: "2025-01-11T12:00:00Z",
            travel_month: "January",
            destination: "Hong Kong",
            acc_manager: "Daniel Baker",
            booking_data: "2024-12-20T23:00:00Z",
            agent: "Lily Adams",
            lead_pax: "Carter Harris",
            order_value: 2250,
            payment_value: 2250,
            transfer_price: 150,
            trip_status: "Pending",
            ops_spoc: "Stella Turner",
            booking_status: "Pending",
            vouchers: "Voucher1313",
        }
    ],
    page: 1,
    limit: 6,
    totalPages: 0,
    isLoading: false,
    error: null,
}

initialState.totalPages = Math.ceil(initialState.data.length / initialState.limit);

const bookingSlice = createSlice({
    name: 'booking',
    initialState,
    reducers: {
        setPage: (state, action) => {
            // set the current page
            state.page = action.payload;
        },
        setLimit: (state, action) => {
            // set the limit of items per page
            state.limit = action.payload;
            // recalculate total pages when limit changes
            state.totalPages = Math.ceil(state.data.length / state.limit);
        },
        setData: (state, action) => {
            // set the data for the booking
            state.data = action.payload;
            // recalculate total pages when data changes
            state.totalPages = Math.ceil(state.data.length / state.limit);
        },
    },
});

export const { setPage, setLimit, setData } = bookingSlice.actions;
export const selectBooking = (state) => state.booking;

export default bookingSlice.reducer;
