import { createSelector, createSlice } from '@reduxjs/toolkit';

const initialState = {
    data: [
        {
            trip_ID: "AB_001111",
            arrival: "20-06-25",
            departure: "20-06-25",
            travel_month: "JUN",
            destination: "Singapore",
            acc_manager: "Pariskishita Gupta",
            booking_data: "20-06-25 ",
            agent: "ABC company Pvt ltd",
            lead_pax: "Jayashtreeee Bachc...2A, 4C(1, 2, 4.8 yrs) dummy text",
            "order_value(USD)": "99,999",
            "payment_value(USD)": "99,999",
            transfer_price: "IDR 30,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "dummy text",
            booking_status: "active",
            vouchers: "10/12",
        },
        {
            trip_ID: "AB_001112",
            arrival: "20-07-15",
            departure: "20-07-25",
            travel_month: "JUL",
            destination: "Bali",
            acc_manager: "John Smith",
            booking_data: "20-06-30",
            agent: "XYZ Travels Ltd",
            lead_pax: "Michael Brown...3A, 2C(5, 7 yrs) family vacation",
            "order_value(USD)": "78,500",
            "payment_value(USD)": "78,500",
            transfer_price: "IDR 25,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Jane Wilson",
            booking_status: "active",
            vouchers: "8/12",
        },
        {
            trip_ID: "AB_001113",
            arrival: "20-08-05",
            departure: "20-08-15",
            travel_month: "AUG",
            destination: "Thailand",
            acc_manager: "Robert Johnson",
            booking_data: "20-07-10",
            agent: "Holiday Express Inc",
            lead_pax: "Sarah Wilson...2A, 1C(3 yrs) honeymoon",
            "order_value(USD)": "56,780",
            "payment_value(USD)": "45,000",
            transfer_price: "IDR 18,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Andy Miller",
            booking_status: "active",
            vouchers: "5/8",
        },
        {
            trip_ID: "AB_001114",
            arrival: "20-09-10",
            departure: "20-09-20",
            travel_month: "SEP",
            destination: "Malaysia",
            acc_manager: "Emily Clark",
            booking_data: "20-08-01",
            agent: "TravelPro Ltd",
            lead_pax: "David Lee...2A, 2C(6, 9 yrs) family trip",
            "order_value(USD)": "67,200",
            "payment_value(USD)": "67,200",
            transfer_price: "IDR 20,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Chris Evans",
            booking_status: "cancelled",
            vouchers: "0/6",
        },
        {
            trip_ID: "AB_001115",
            arrival: "20-10-05",
            departure: "20-10-15",
            travel_month: "OCT",
            destination: "Japan",
            acc_manager: "Sophia Turner",
            booking_data: "20-09-10",
            agent: "Asia Tours",
            lead_pax: "Olivia Kim...1A, 1C(8 yrs) autumn tour",
            "order_value(USD)": "120,000",
            "payment_value(USD)": "100,000",
            transfer_price: "IDR 40,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Liam Carter",
            booking_status: "pending",
            vouchers: "3/10",
        },
        {
            trip_ID: "AB_001116",
            arrival: "20-11-12",
            departure: "20-11-22",
            travel_month: "NOV",
            destination: "Vietnam",
            acc_manager: "Lucas White",
            booking_data: "20-10-15",
            agent: "Holiday Makers",
            lead_pax: "Emma Watson...2A, 1C(5 yrs) adventure",
            "order_value(USD)": "88,000",
            "payment_value(USD)": "88,000",
            transfer_price: "IDR 22,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Noah Scott",
            booking_status: "active",
            vouchers: "7/9",
        },
        {
            trip_ID: "AB_001117",
            arrival: "20-12-01",
            departure: "20-12-10",
            travel_month: "DEC",
            destination: "Dubai",
            acc_manager: "Mia Lewis",
            booking_data: "20-11-05",
            agent: "Luxury Travels",
            lead_pax: "William Brown...2A, 2C(3, 6 yrs) luxury trip",
            "order_value(USD)": "200,000",
            "payment_value(USD)": "150,000",
            transfer_price: "IDR 60,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Ava Walker",
            booking_status: "active",
            vouchers: "12/12",
        },
        {
            trip_ID: "AB_001118",
            arrival: "21-01-15",
            departure: "21-01-25",
            travel_month: "JAN",
            destination: "Australia",
            acc_manager: "Ethan Hall",
            booking_data: "20-12-10",
            agent: "Down Under Tours",
            lead_pax: "James Smith...2A, 1C(10 yrs) summer holiday",
            "order_value(USD)": "175,000",
            "payment_value(USD)": "175,000",
            transfer_price: "IDR 55,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Charlotte King",
            booking_status: "pending",
            vouchers: "10/10",
        },
        {
            trip_ID: "AB_001119",
            arrival: "21-02-10",
            departure: "21-02-20",
            travel_month: "FEB",
            destination: "New Zealand",
            acc_manager: "Benjamin Young",
            booking_data: "21-01-05",
            agent: "Kiwi Adventures",
            lead_pax: "Lucas Green...1A, 2C(7, 9 yrs) adventure",
            "order_value(USD)": "98,000",
            "payment_value(USD)": "90,000",
            transfer_price: "IDR 30,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Amelia Wright",
            booking_status: "active",
            vouchers: "6/8",
        },
        {
            trip_ID: "AB_001120",
            arrival: "21-03-05",
            departure: "21-03-15",
            travel_month: "MAR",
            destination: "Maldives",
            acc_manager: "Ella Harris",
            booking_data: "21-02-01",
            agent: "Island Getaways",
            lead_pax: "Mason Lee...2A honeymoon",
            "order_value(USD)": "150,000",
            "payment_value(USD)": "150,000",
            transfer_price: "IDR 45,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Harper Martin",
            booking_status: "active",
            vouchers: "8/8",
        },
        {
            trip_ID: "AB_001121",
            arrival: "21-04-10",
            departure: "21-04-20",
            travel_month: "APR",
            destination: "Sri Lanka",
            acc_manager: "Henry Clark",
            booking_data: "21-03-05",
            agent: "Ceylon Tours",
            lead_pax: "Sophie Adams...2A, 1C(4 yrs) beach holiday",
            "order_value(USD)": "60,000",
            "payment_value(USD)": "60,000",
            transfer_price: "IDR 15,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Jack Lee",
            booking_status: "cancelled",
            vouchers: "0/5",
        },
        {
            trip_ID: "AB_001122",
            arrival: "21-05-15",
            departure: "21-05-25",
            travel_month: "MAY",
            destination: "Nepal",
            acc_manager: "Grace Turner",
            booking_data: "21-04-10",
            agent: "Himalaya Treks",
            lead_pax: "Daniel Kim...1A, 1C(12 yrs) trekking",
            "order_value(USD)": "85,000",
            "payment_value(USD)": "80,000",
            transfer_price: "IDR 18,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Lily Evans",
            booking_status: "pending",
            vouchers: "4/7",
        },
        {
            trip_ID: "AB_001123",
            arrival: "21-06-01",
            departure: "21-06-10",
            travel_month: "JUN",
            destination: "Hong Kong",
            acc_manager: "Samuel Baker",
            booking_data: "21-05-05",
            agent: "City Lights Travel",
            lead_pax: "Chloe Brown...2A, 2C(8, 11 yrs) city tour",
            "order_value(USD)": "110,000",
            "payment_value(USD)": "110,000",
            transfer_price: "IDR 35,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Zoe Carter",
            booking_status: "active",
            vouchers: "9/10",
        },
        {
            trip_ID: "AB_001124",
            arrival: "21-07-12",
            departure: "21-07-22",
            travel_month: "JUL",
            destination: "South Korea",
            acc_manager: "Victoria Hill",
            booking_data: "21-06-10",
            agent: "Korea Discovery",
            lead_pax: "Matthew Lee...2A, 1C(6 yrs) culture trip",
            "order_value(USD)": "95,000",
            "payment_value(USD)": "90,000",
            transfer_price: "IDR 28,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Ella Moore",
            booking_status: "active",
            vouchers: "7/7",
        },
        {
            trip_ID: "AB_001125",
            arrival: "21-08-05",
            departure: "21-08-15",
            travel_month: "AUG",
            destination: "Cambodia",
            acc_manager: "Oliver Adams",
            booking_data: "21-07-01",
            agent: "Angkor Tours",
            lead_pax: "Aiden Clark...2A, 2C(5, 9 yrs) temples",
            "order_value(USD)": "70,000",
            "payment_value(USD)": "70,000",
            transfer_price: "IDR 19,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Mila Lewis",
            booking_status: "cancelled",
            vouchers: "0/6",
        },
        {
            trip_ID: "AB_001126",
            arrival: "21-09-10",
            departure: "21-09-20",
            travel_month: "SEP",
            destination: "Laos",
            acc_manager: "Lucas Turner",
            booking_data: "21-08-05",
            agent: "Mekong Travels",
            lead_pax: "Ella Kim...1A, 1C(7 yrs) river cruise",
            "order_value(USD)": "65,000",
            "payment_value(USD)": "60,000",
            transfer_price: "IDR 16,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Mason White",
            booking_status: "pending",
            vouchers: "3/5",
        },
        {
            trip_ID: "AB_001127",
            arrival: "21-10-15",
            departure: "21-10-25",
            travel_month: "OCT",
            destination: "Philippines",
            acc_manager: "Ava Harris",
            booking_data: "21-09-10",
            agent: "Island Hoppers",
            lead_pax: "Sofia Lee...2A, 1C(9 yrs) island tour",
            "order_value(USD)": "80,000",
            "payment_value(USD)": "80,000",
            transfer_price: "IDR 21,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Ethan Scott",
            booking_status: "active",
            vouchers: "6/8",
        },
        {
            trip_ID: "AB_001128",
            arrival: "21-11-01",
            departure: "21-11-10",
            travel_month: "NOV",
            destination: "India",
            acc_manager: "Jack Martin",
            booking_data: "21-10-05",
            agent: "Incredible India",
            lead_pax: "Liam Brown...2A, 2C(6, 12 yrs) heritage",
            "order_value(USD)": "105,000",
            "payment_value(USD)": "100,000",
            transfer_price: "IDR 32,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Grace Evans",
            booking_status: "active",
            vouchers: "10/10",
        },
        {
            trip_ID: "AB_001129",
            arrival: "21-12-12",
            departure: "21-12-22",
            travel_month: "DEC",
            destination: "China",
            acc_manager: "Mia Walker",
            booking_data: "21-11-10",
            agent: "Great Wall Tours",
            lead_pax: "Benjamin Lee...2A, 1C(8 yrs) winter trip",
            "order_value(USD)": "130,000",
            "payment_value(USD)": "120,000",
            transfer_price: "IDR 38,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Henry Carter",
            booking_status: "cancelled",
            vouchers: "0/9",
        },
        {
            trip_ID: "AB_001130",
            arrival: "22-01-05",
            departure: "22-01-15",
            travel_month: "JAN",
            destination: "Turkey",
            acc_manager: "Emily Adams",
            booking_data: "21-12-01",
            agent: "Anatolia Travels",
            lead_pax: "Charlotte Kim...2A, 2C(5, 10 yrs) history",
            "order_value(USD)": "115,000",
            "payment_value(USD)": "110,000",
            transfer_price: "IDR 33,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Samuel Lee",
            booking_status: "pending",
            vouchers: "5/8",
        },
        {
            trip_ID: "AB_001131",
            arrival: "22-02-10",
            departure: "22-02-20",
            travel_month: "FEB",
            destination: "Egypt",
            acc_manager: "Oliver Harris",
            booking_data: "22-01-05",
            agent: "Pyramid Tours",
            lead_pax: "Amelia Brown...2A, 1C(7 yrs) pyramids",
            "order_value(USD)": "140,000",
            "payment_value(USD)": "140,000",
            transfer_price: "IDR 42,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Victoria Scott",
            booking_status: "active",
            vouchers: "8/10",
        },
        {
            trip_ID: "AB_001132",
            arrival: "22-03-15",
            departure: "22-03-25",
            travel_month: "MAR",
            destination: "Greece",
            acc_manager: "Sophia Lee",
            booking_data: "22-02-10",
            agent: "Aegean Holidays",
            lead_pax: "James Kim...2A honeymoon",
            "order_value(USD)": "160,000",
            "payment_value(USD)": "150,000",
            transfer_price: "IDR 48,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Lucas Evans",
            booking_status: "active",
            vouchers: "12/12",
        },
        {
            trip_ID: "AB_001133",
            arrival: "22-04-10",
            departure: "22-04-20",
            travel_month: "APR",
            destination: "Italy",
            acc_manager: "Henry Turner",
            booking_data: "22-03-05",
            agent: "Roman Holidays",
            lead_pax: "Mia Clark...2A, 1C(9 yrs) culture",
            "order_value(USD)": "125,000",
            "payment_value(USD)": "120,000",
            transfer_price: "IDR 36,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Ella White",
            booking_status: "cancelled",
            vouchers: "0/7",
        },
        {
            trip_ID: "AB_001134",
            arrival: "22-05-12",
            departure: "22-05-22",
            travel_month: "MAY",
            destination: "France",
            acc_manager: "Grace Harris",
            booking_data: "22-04-10",
            agent: "Paris Dreams",
            lead_pax: "William Lee...2A, 2C(6, 11 yrs) sightseeing",
            "order_value(USD)": "135,000",
            "payment_value(USD)": "130,000",
            transfer_price: "IDR 39,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Jack Martin",
            booking_status: "pending",
            vouchers: "6/9",
        },
        {
            trip_ID: "AB_001135",
            arrival: "22-06-01",
            departure: "22-06-10",
            travel_month: "JUN",
            destination: "Spain",
            acc_manager: "Samuel Adams",
            booking_data: "22-05-05",
            agent: "Iberian Tours",
            lead_pax: "Sophie Kim...2A, 1C(8 yrs) summer",
            "order_value(USD)": "110,000",
            "payment_value(USD)": "110,000",
            transfer_price: "IDR 32,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Zoe Harris",
            booking_status: "active",
            vouchers: "7/8",
        },
        {
            trip_ID: "AB_001136",
            arrival: "22-07-10",
            departure: "22-07-20",
            travel_month: "JUL",
            destination: "Germany",
            acc_manager: "Victoria Lee",
            booking_data: "22-06-10",
            agent: "Euro Travels",
            lead_pax: "Matthew Brown...2A, 2C(5, 9 yrs) castles",
            "order_value(USD)": "120,000",
            "payment_value(USD)": "115,000",
            transfer_price: "IDR 34,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Ella Turner",
            booking_status: "active",
            vouchers: "9/9",
        },
        {
            trip_ID: "AB_001137",
            arrival: "22-08-05",
            departure: "22-08-15",
            travel_month: "AUG",
            destination: "Switzerland",
            acc_manager: "Oliver Clark",
            booking_data: "22-07-01",
            agent: "Alpine Holidays",
            lead_pax: "Aiden Harris...2A, 1C(7 yrs) mountains",
            "order_value(USD)": "145,000",
            "payment_value(USD)": "140,000",
            transfer_price: "IDR 41,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Mila Adams",
            booking_status: "cancelled",
            vouchers: "0/8",
        },
        {
            trip_ID: "AB_001138",
            arrival: "22-09-10",
            departure: "22-09-20",
            travel_month: "SEP",
            destination: "Austria",
            acc_manager: "Lucas Harris",
            booking_data: "22-08-05",
            agent: "Vienna Travels",
            lead_pax: "Ella Lee...1A, 1C(6 yrs) music tour",
            "order_value(USD)": "100,000",
            "payment_value(USD)": "95,000",
            transfer_price: "IDR 29,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Mason Turner",
            booking_status: "pending",
            vouchers: "4/6",
        },
        {
            trip_ID: "AB_001139",
            arrival: "22-10-15",
            departure: "22-10-25",
            travel_month: "OCT",
            destination: "Netherlands",
            acc_manager: "Ava Adams",
            booking_data: "22-09-10",
            agent: "Tulip Tours",
            lead_pax: "Sofia Harris...2A, 1C(8 yrs) tulip season",
            "order_value(USD)": "105,000",
            "payment_value(USD)": "100,000",
            transfer_price: "IDR 31,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Ethan Lee",
            booking_status: "active",
            vouchers: "6/7",
        },
        {
            trip_ID: "AB_001140",
            arrival: "22-11-01",
            departure: "22-11-10",
            travel_month: "NOV",
            destination: "Belgium",
            acc_manager: "Jack Harris",
            booking_data: "22-10-05",
            agent: "Choco Tours",
            lead_pax: "Liam Adams...2A, 2C(7, 12 yrs) chocolate",
            "order_value(USD)": "115,000",
            "payment_value(USD)": "110,000",
            transfer_price: "IDR 33,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Grace Turner",
            booking_status: "active",
            vouchers: "8/8",
        },
        {
            trip_ID: "AB_001141",
            arrival: "22-12-12",
            departure: "22-12-22",
            travel_month: "DEC",
            destination: "UK",
            acc_manager: "Mia Adams",
            booking_data: "22-11-10",
            agent: "Britannia Travels",
            lead_pax: "Benjamin Harris...2A, 1C(9 yrs) Christmas",
            "order_value(USD)": "140,000",
            "payment_value(USD)": "135,000",
            transfer_price: "IDR 40,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Henry Lee",
            booking_status: "cancelled",
            vouchers: "0/9",
        },
        {
            trip_ID: "AB_001142",
            arrival: "23-01-05",
            departure: "23-01-15",
            travel_month: "JAN",
            destination: "Ireland",
            acc_manager: "Emily Harris",
            booking_data: "22-12-01",
            agent: "Emerald Tours",
            lead_pax: "Charlotte Adams...2A, 2C(6, 10 yrs) castles",
            "order_value(USD)": "120,000",
            "payment_value(USD)": "120,000",
            transfer_price: "IDR 36,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Samuel Harris",
            booking_status: "pending",
            vouchers: "7/10",
        },
        {
            trip_ID: "AB_001143",
            arrival: "23-02-10",
            departure: "23-02-20",
            travel_month: "FEB",
            destination: "Portugal",
            acc_manager: "Oliver Adams",
            booking_data: "23-01-05",
            agent: "Lisbon Travels",
            lead_pax: "Amelia Lee...2A, 1C(8 yrs) coast",
            "order_value(USD)": "110,000",
            "payment_value(USD)": "105,000",
            transfer_price: "IDR 32,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Victoria Harris",
            booking_status: "active",
            vouchers: "6/8",
        },
        {
            trip_ID: "AB_001144",
            arrival: "23-03-15",
            departure: "23-03-25",
            travel_month: "MAR",
            destination: "Norway",
            acc_manager: "Sophia Adams",
            booking_data: "23-02-10",
            agent: "Fjord Tours",
            lead_pax: "James Harris...2A, 1C(7 yrs) fjords",
            "order_value(USD)": "130,000",
            "payment_value(USD)": "125,000",
            transfer_price: "IDR 38,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Lucas Harris",
            booking_status: "active",
            vouchers: "9/9",
        },
        {
            trip_ID: "AB_001145",
            arrival: "23-04-10",
            departure: "23-04-20",
            travel_month: "APR",
            destination: "Sweden",
            acc_manager: "Henry Adams",
            booking_data: "23-03-05",
            agent: "Nordic Travels",
            lead_pax: "Mia Harris...2A, 2C(5, 11 yrs) spring",
            "order_value(USD)": "125,000",
            "payment_value(USD)": "120,000",
            transfer_price: "IDR 36,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Ella Harris",
            booking_status: "cancelled",
            vouchers: "0/7",
        },
        {
            trip_ID: "AB_001146",
            arrival: "23-05-12",
            departure: "23-05-22",
            travel_month: "MAY",
            destination: "Denmark",
            acc_manager: "Grace Adams",
            booking_data: "23-04-10",
            agent: "Copenhagen Tours",
            lead_pax: "William Harris...2A, 1C(8 yrs) city break",
            "order_value(USD)": "115,000",
            "payment_value(USD)": "110,000",
            transfer_price: "IDR 33,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Jack Harris",
            booking_status: "pending",
            vouchers: "5/8",
        },
        {
            trip_ID: "AB_001147",
            arrival: "23-06-01",
            departure: "23-06-10",
            travel_month: "JUN",
            destination: "Finland",
            acc_manager: "Samuel Adams",
            booking_data: "23-05-05",
            agent: "Helsinki Holidays",
            lead_pax: "Sophie Harris...2A, 1C(7 yrs) lakes",
            "order_value(USD)": "110,000",
            "payment_value(USD)": "105,000",
            transfer_price: "IDR 32,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Zoe Adams",
            booking_status: "active",
            vouchers: "7/8",
        },
        {
            trip_ID: "AB_001148",
            arrival: "23-07-10",
            departure: "23-07-20",
            travel_month: "JUL",
            destination: "Russia",
            acc_manager: "Victoria Adams",
            booking_data: "23-06-10",
            agent: "Moscow Travels",
            lead_pax: "Matthew Harris...2A, 2C(6, 10 yrs) history",
            "order_value(USD)": "120,000",
            "payment_value(USD)": "115,000",
            transfer_price: "IDR 34,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Ella Adams",
            booking_status: "active",
            vouchers: "9/9",
        },
        {
            trip_ID: "AB_001149",
            arrival: "23-08-05",
            departure: "23-08-15",
            travel_month: "AUG",
            destination: "Poland",
            acc_manager: "Oliver Harris",
            booking_data: "23-07-01",
            agent: "Warsaw Tours",
            lead_pax: "Aiden Adams...2A, 1C(7 yrs) culture",
            "order_value(USD)": "115,000",
            "payment_value(USD)": "110,000",
            transfer_price: "IDR 33,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Mila Harris",
            booking_status: "cancelled",
            vouchers: "0/8",
        },
        {
            trip_ID: "AB_001150",
            arrival: "23-09-10",
            departure: "23-09-20",
            travel_month: "SEP",
            destination: "Czech Republic",
            acc_manager: "Lucas Adams",
            booking_data: "23-08-05",
            agent: "Prague Travels",
            lead_pax: "Ella Harris...1A, 1C(6 yrs) castles",
            "order_value(USD)": "100,000",
            "payment_value(USD)": "95,000",
            transfer_price: "IDR 29,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Mason Adams",
            booking_status: "pending",
            vouchers: "4/6",
        },
        {
            trip_ID: "AB_001151",
            arrival: "23-10-15",
            departure: "23-10-25",
            travel_month: "OCT",
            destination: "Hungary",
            acc_manager: "Ava Harris",
            booking_data: "23-09-10",
            agent: "Budapest Tours",
            lead_pax: "Sofia Adams...2A, 1C(8 yrs) river cruise",
            "order_value(USD)": "105,000",
            "payment_value(USD)": "100,000",
            transfer_price: "IDR 31,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Ethan Adams",
            booking_status: "active",
            vouchers: "6/7",
        },
        {
            trip_ID: "AB_001152",
            arrival: "23-11-01",
            departure: "23-11-10",
            travel_month: "NOV",
            destination: "Croatia",
            acc_manager: "Jack Adams",
            booking_data: "23-10-05",
            agent: "Adriatic Travels",
            lead_pax: "Liam Harris...2A, 2C(7, 12 yrs) coast",
            "order_value(USD)": "115,000",
            "payment_value(USD)": "110,000",
            transfer_price: "IDR 33,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Grace Adams",
            booking_status: "active",
            vouchers: "8/8",
        },
        {
            trip_ID: "AB_001153",
            arrival: "23-12-12",
            departure: "23-12-22",
            travel_month: "DEC",
            destination: "Slovenia",
            acc_manager: "Mia Harris",
            booking_data: "23-11-10",
            agent: "Lake Bled Tours",
            lead_pax: "Benjamin Adams...2A, 1C(9 yrs) winter",
            "order_value(USD)": "140,000",
            "payment_value(USD)": "135,000",
            transfer_price: "IDR 40,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Henry Adams",
            booking_status: "cancelled",
            vouchers: "0/9",
        },
        {
            trip_ID: "AB_001154",
            arrival: "24-01-05",
            departure: "24-01-15",
            travel_month: "JAN",
            destination: "Iceland",
            acc_manager: "Emily Adams",
            booking_data: "23-12-01",
            agent: "Aurora Travels",
            lead_pax: "Charlotte Harris...2A, 2C(6, 10 yrs) northern lights",
            "order_value(USD)": "120,000",
            "payment_value(USD)": "120,000",
            transfer_price: "IDR 36,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Samuel Adams",
            booking_status: "pending",
            vouchers: "7/10",
        },
        {
            trip_ID: "AB_001155",
            arrival: "24-02-10",
            departure: "24-02-20",
            travel_month: "FEB",
            destination: "Estonia",
            acc_manager: "Oliver Adams",
            booking_data: "24-01-05",
            agent: "Baltic Travels",
            lead_pax: "Amelia Adams...2A, 1C(8 yrs) old town",
            "order_value(USD)": "110,000",
            "payment_value(USD)": "105,000",
            transfer_price: "IDR 32,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Victoria Adams",
            booking_status: "active",
            vouchers: "6/8",
        },
        {
            trip_ID: "AB_001156",
            arrival: "24-03-15",
            departure: "24-03-25",
            travel_month: "MAR",
            destination: "Latvia",
            acc_manager: "Sophia Adams",
            booking_data: "24-02-10",
            agent: "Riga Travels",
            lead_pax: "James Adams...2A, 1C(7 yrs) city break",
            "order_value(USD)": "130,000",
            "payment_value(USD)": "125,000",
            transfer_price: "IDR 38,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Lucas Adams",
            booking_status: "active",
            vouchers: "9/9",
        },
        {
            trip_ID: "AB_001157",
            arrival: "24-04-10",
            departure: "24-04-20",
            travel_month: "APR",
            destination: "Lithuania",
            acc_manager: "Henry Adams",
            booking_data: "24-03-05",
            agent: "Vilnius Travels",
            lead_pax: "Mia Adams...2A, 2C(5, 11 yrs) spring",
            "order_value(USD)": "125,000",
            "payment_value(USD)": "120,000",
            transfer_price: "IDR 36,00,000,000",
            trip_status: "Cancelled",
            ops_spoc: "Ella Adams",
            booking_status: "cancelled",
            vouchers: "0/7",
        },
        {
            trip_ID: "AB_001158",
            arrival: "24-05-12",
            departure: "24-05-22",
            travel_month: "MAY",
            destination: "Luxembourg",
            acc_manager: "Grace Adams",
            booking_data: "24-04-10",
            agent: "Lux Travels",
            lead_pax: "William Adams...2A, 1C(8 yrs) city break",
            "order_value(USD)": "115,000",
            "payment_value(USD)": "110,000",
            transfer_price: "IDR 33,00,000,000",
            trip_status: "Confirmed",
            ops_spoc: "Jack Adams",
            booking_status: "pending",
            vouchers: "5/8",
        },
        {
            trip_ID: "AB_001159",
            arrival: "24-06-01",
            departure: "24-06-10",
            travel_month: "JUN",
            destination: "Monaco",
            acc_manager: "Samuel Adams",
            booking_data: "24-05-05",
            agent: "Monte Carlo Travels",
            lead_pax: "Sophie Adams...2A, 1C(7 yrs) luxury",
            "order_value(USD)": "110,000",
            "payment_value(USD)": "105,000",
            transfer_price: "IDR 32,00,000,000",
            trip_status: "On Tour",
            ops_spoc: "Zoe Adams",
            booking_status: "active",
            vouchers: "7/8",
        },
        {
            trip_ID: "AB_001160",
            arrival: "24-07-10",
            departure: "24-07-20",
            travel_month: "JUL",
            destination: "Liechtenstein",
            acc_manager: "Victoria Adams",
            booking_data: "24-06-10",
            agent: "Alpine Travels",
            lead_pax: "Matthew Adams...2A, 2C(6, 10 yrs) mountains",
            "order_value(USD)": "120,000",
            "payment_value(USD)": "115,000",
            transfer_price: "IDR 34,00,000,000",
            trip_status: "Travelled",
            ops_spoc: "Ella Adams",
            booking_status: "active",
            vouchers: "9/9",
        },
    ],
    page: 1,
    limit: 6,
    totalPages: 0,
    filter: {
        trip_ID: '',
        arrival: '',
        departure: '',
        travel_month: '',
        destination: '',
        acc_manager: '',
        booking_data: '',
        agent: '',
        lead_pax: '',
        "order_value(USD)": '',
        "payment_value(USD)": '',
        transfer_price: '',
        trip_status: '',
        ops_spoc: '',
        booking_status: '',
        vouchers: '',
    },
    sortBy: '',
    isLoading: false,
    error: null,
}

initialState.totalPages = Math.ceil(initialState.data.length / initialState.limit);

initialState.filterData = [
    { type: "search", placeholder: "Lead pax/Trip id", name: "trip_ID" },
    {
        type: "select",
        placeholder: "Destination",
        name: "destination",
        options: initialState.data.map(item => item.destination).filter((value, index, self) => self.indexOf(value) === index),
    },
    {
        type: "select",
        placeholder: "Travel Month",
        name: "travel_month",
        options: ["All", "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"],
    },
    {
        type: "select",
        placeholder: "Sort by",
        name: "sort_by",
        options: ["All", "Arrival", "Departure", "Travel Month", "Destination", "Acc. Manager", "Booking Date", "Agent", "Lead Pax", "Order Value(USD)", "Payment Value(USD)", "Transfer Price", "Trip Status", "Ops SPOC", "Booking Status", "Vouchers"],
        disabled: true,
    },
    {
        type: "select",
        placeholder: "Acc. Manager",
        name: "acc_manager",
        options: initialState.data.map(item => item.acc_manager).filter((value, index, self) => self.indexOf(value) === index),
    },
    { type: "search", placeholder: "Agent", name: "agent" },
    {
        type: "select",
        placeholder: "Trip status",
        name: "trip_status",
        options: ["All", "Confirmed", "On Tour", "Travelled", "Cancelled", "Pending"],
    },
]

const bookingSlice = createSlice({
    name: 'booking',
    initialState,
    reducers: {
        setPage: (state, action) => {
            // set the current page
            state.page = action.payload;
        },
        setLimit: (state, action) => {
            // set the limit of items per page
            state.limit = action.payload;
            // recalculate total pages when limit changes
            state.totalPages = Math.ceil(state.data.length / state.limit);
        },
        setData: (state, action) => {
            // set the data for the booking
            state.data = action.payload;
            // recalculate total pages when data changes
            state.totalPages = Math.ceil(state.data.length / state.limit);
        },
        setFilter: (state, action) => {
            // set the filter criteria
            state.filter = { ...state.filter, ...action.payload };
        },
        clearFilter: (state) => {
            // clear the filter criteria
            state.filter = {
                trip_ID: '',
                arrival: '',
                departure: '',
                travel_month: '',
                destination: '',
                acc_manager: '',
                booking_data: '',
                agent: '',
                lead_pax: '',
                "order_value(USD)": '',
                "payment_value(USD)": '',
                transfer_price: '',
                trip_status: '',
                ops_spoc: '',
                booking_status: '',
                vouchers: '',
            };
        },
    },
});

export const { setPage, setLimit, setData, setFilter, clearFilter } = bookingSlice.actions;
export const selectBooking = (state) => state.booking;
export const selectFilteredData = createSelector(
    [selectBooking],
    (booking) => {
        const { data, filter, page, limit } = booking;
        const { sort_by } = filter;

        console.log("Sorting by:", sort_by);
        

        // Filtering
        const filteredData = data.filter((item) => {
            return Object.keys(filter).every((key) => {
                if (!filter[key] || key === "sort_by") return true;
                return item[key]?.toString().toLowerCase().includes(filter[key].toLowerCase());
            });
        });

        // Sorting
        let sortedData = [...filteredData];
        if (sort_by && sort_by !== "All") {
            sortedData.sort((a, b) => {
                const aValue = a[sort_by];
                const bValue = b[sort_by];

                // Helper: check if value matches date format YY-MM-DD
                const isDate = (val) => typeof val === "string" && /^\d{2}-\d{2}-\d{2}$/.test(val);

                if (isDate(aValue) && isDate(bValue)) {
                    // Parse as date: convert to '20YY-MM-DD'
                    const parseDate = (val) => {
                        const [yy, mm, dd] = val.split("-");
                        return new Date(`20${yy}-${mm}-${dd}`);
                    };
                    return parseDate(aValue) - parseDate(bValue);
                }

                // Numeric sort (remove commas and currency symbols)
                const numA = Number(aValue?.toString().replace(/[^\d.-]/g, ""));
                const numB = Number(bValue?.toString().replace(/[^\d.-]/g, ""));
                if (!isNaN(numA) && !isNaN(numB)) {
                    return numA - numB;
                }

                // String sort
                return aValue?.toString().localeCompare(bValue?.toString());
            });
        }

        // Pagination
        const startIndex = (page - 1) * limit;
        const endIndex = startIndex + limit;
        return {
            data: sortedData.slice(startIndex, endIndex),
            totalPages: Math.ceil(sortedData.length / limit),
            currentPage: page,
        };
    }
);
export const selectFilterData = (state) => state.booking.filterData;
export const selectFilter = (state) => state.booking.filter;

export default bookingSlice.reducer;
